### ISSUE TITLE
Subsettools returning extra dummy layers 

### ISSUE THREAD

**Issue by hstone31** [hydroframe/subsettools#71]
Sometimes when running a water year for my HUC-8 subbasin the data_accessor returns 7 dummy layers to the top.
For example in the .pfidb the ComputationalGrid.NZ is assigned a value of 17
`data = run.data_accessor`
`data.shape `
`(17, 66, 80) # should be 10, 66, 80`

**Comment by gartavanis** [comment]
Addressed in PR #72
