### ISSUE TITLE
JOSS/review/code

### ISSUE THREAD

**Issue by JannisHoch** [hydroframe/subsettools#86]
Overall, the code is well documented and the readthedoc documentation is exhaustive.

To finalise the JOSS review, some minor comments need to be adressed still.

- [ ] In https://hydroframesubsettools.readthedocs.io/en/latest/example_notebooks/example_notebooks.html, it would be great if it is mentioned that the notebooks can be run via Binder, and that a Princeton HydroGEN PIN is necessary. Great btw that acquiring the PIN is very straightforward!
- [ ] With respect to the notebooks available on https://hydroframesubsettools.readthedocs.io/en/latest/example_notebooks/example_notebooks.html: it would be good to mention how to run the notebooks locally. Not a big deal if one is used to work with these notebooks, but since your packages is intended for less experiences users, more information would be useful.
- [ ] It is not possible to run `pytest` in the `test` folder due to the following error message: `FileNotFoundError: [Errno 2] No such file or directory: 'tests/correct_output/upstream_mask_lower_delaware.npy'`. Would it be possible to make the files necessary for the tests available?

Many thanks!

**Comment by gartavanis** [comment]
Thank you, @JannisHoch, for your comments. We will address them below:

1 and 2: We have updated the documentation on ReadTheDocs to provide instructions for running the notebooks on Binder, Docker and on one's local machine. Glad to hear that the HydroGEN PIN was easy to get and use!

3: Are you running `pytest` from the root of the subsettools directory (i.e. above the "tests" directory)? I can see the delaware file exists on the repo (https://github.com/hydroframe/subsettools/tree/main/tests/correct_output), so I wonder if it's an issue with the directory from which `pytest` is run.

**Comment by JannisHoch** [comment]
Hi @gartavanis,

thanks for updating the RTD documentation.

Regarding `pytest`, this is what I get when running `pytest` in `subsettools/tests` in branch `main`:

```
======================================================================================================= ERRORS =======================================================================================================
_______________________________________________________________________________________ ERROR collecting tests/test_domain.py ________________________________________________________________________________________
test_domain.py:127: in <module>
    np.load("tests/correct_output/upstream_mask_lower_delaware.npy"),
../../../../opt/anaconda3/envs/subsettools/lib/python3.11/site-packages/numpy/lib/_npyio_impl.py:455: in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
E   FileNotFoundError: [Errno 2] No such file or directory: 'tests/correct_output/upstream_mask_lower_delaware.npy'
============================================================================================== short test summary info ===============================================================================================
ERROR test_domain.py - FileNotFoundError: [Errno 2] No such file or directory: 'tests/correct_output/upstream_mask_lower_delaware.npy'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================================== 1 error in 3.13s ==================================================================================================
```

**Comment by JannisHoch** [comment]
Indeed, if I execute `pytest` in the main directory, executes tests but fails on 16 tests (see attachment)?

[subsettools_pytest.txt](https://github.com/user-attachments/files/16062999/subsettools_pytest.txt)

**Comment by gartavanis** [comment]
Thanks for sharing the pytest logs, @JannisHoch.

I would run the tests in the main branch. We've made them easier to run than the joss-paper branch.

To provide a HydroGEN PIN for the tests, open the file `subsettools/tests/conftest.py`, uncomment lines 5 and 7 and provide your email and PIN. 

After doing that, all the tests that check pure subsettools functionality should pass. In addition, there are three test files (test_conus1_upper_verde.py, test_conus1_upper_verde_spinup.py and test_multiple_hucs.py) that check integration with ParFlow. These tests require an installation of ParFlow to run. As ParFlow can be tricky to install, the easiest way would be to run them in our ParFlow Docker container.

If you would like to run the ParFlow integration tests as well, you can:

1. Get our Docker container (https://hydroframesubsettools.readthedocs.io/en/latest/getting_started.html#using-docker)
2. Open a terminal inside the container and do:

```bash
$ pip install pytest
$ git clone https://github.com/hydroframe/subsettools.git
```

Then, you can edit the `conftest.py` file as described above and run `pytest`.

There is a test in test_conus1_upper_verde.py, which I expect to fail. It requires 16 cores to run ParFlow, and most users don't have access to such systems. This tests doesn't check any additional subsettools functionality and doesn't add to the integration testing. It just makes the test suite harder to run, so I'm going to remove it from the test suite soon.

Thanks again for your time and effort!

**Comment by JannisHoch** [comment]
Ah okay great, thanks for the explanation.
Would be good to mention somewhere how to provide the PIN and mail for the tests. Since running the tests seems to be rather elaborate, I could imagine there is a case for a dedicated section about it?

**Comment by gartavanis** [comment]
Thanks for the suggestion, @JannisHoch!
I've added a "Running the test suite" section to the Contributing page in the documentation with instructions.
I've also removed the test that requires 16 cores so that should no longer be an issue.

**Comment by JannisHoch** [comment]
great, thanks!
